-- Central species visual geometry for True Size (visual only; 1-cell footprint).
-- Data generated by tools/generate_true_size_runtime.py into
-- assets/generated/true_size/species_table.lua (+ species_geometry.json).
local V = ...
local JsonDecode = V.require("json_decode")

local SpeciesGeometry = {}

SpeciesGeometry.SIZE_CLASSES = {
  XS  = { minH = 14, maxH = 16, label = "XS" },
  S   = { minH = 17, maxH = 20, label = "S" },
  M   = { minH = 21, maxH = 24, label = "M" },
  L   = { minH = 25, maxH = 29, label = "L" },
  XL  = { minH = 30, maxH = 35, label = "XL" },
  XXL = { minH = 36, maxH = 42, label = "XXL" },
}

-- Documentation / legacy class→cell map (no longer the live spacing authority).
SpeciesGeometry.FOLLOW_GAP_BY_CLASS = {
  XS = 1,
  S = 1,
  M = 1,
  L = 1,
  XL = 2,
  XXL = 2,
}

-- Continuous True Size follower spacing (pixels along trail history).
SpeciesGeometry.CELL_PX = 16
SpeciesGeometry.GAP_PX_MIN = 16
SpeciesGeometry.GAP_PX_TYPICAL_MAX = 28
SpeciesGeometry.GAP_PX_OVERRIDE_MAX = 36
-- Hysteresis thresholds when mapping desired px → sticky trail-cell lag.
SpeciesGeometry.GAP_HYSTERESIS_UP_PX = 25   -- 1 → 2
SpeciesGeometry.GAP_HYSTERESIS_DOWN_PX = 21 -- 2 → 1
SpeciesGeometry.FRONT_OVERHANG_FACTOR = 0.50
SpeciesGeometry.BACK_OVERHANG_FACTOR = 0.30

-- Exceptional desired-gap floor in pixels (not coarse 3-cell jumps).
SpeciesGeometry.FOLLOW_GAP_PX_OVERRIDES = {
  [95] = 32,  -- Onix
  [130] = 34, -- Gyarados
  [131] = 26, -- Lapras
  [143] = 26, -- Snorlax
}

-- Deprecated cell overrides — kept as empty alias so old readers don't nil-index.
SpeciesGeometry.FOLLOW_GAP_OVERRIDES = {}

SpeciesGeometry.TABLE_REL = "assets/generated/true_size/species_table.lua"
SpeciesGeometry.JSON_REL = "assets/generated/true_size/species_geometry.json"

local _table = nil
local _loadError = nil

local function readBytes(mod, rel)
  if mod and type(mod.read) == "function" then
    local ok, data = pcall(mod.read, mod, rel)
    if ok and type(data) == "string" and data ~= "" then return data end
  end
  local f = io.open(rel, "rb")
  if not f and V.path then
    f = io.open((V.path or ".") .. "/" .. rel, "rb")
  end
  if f then
    local data = f:read("*a")
    f:close()
    if type(data) == "string" and data ~= "" then return data end
  end
  return nil
end

function SpeciesGeometry.load(mod)
  if _table ~= nil then return _table, _loadError end
  local src = readBytes(mod or V.mod, SpeciesGeometry.TABLE_REL)
  if type(src) == "string" then
    local loader = loadstring or load
    local chunk, err = loader(src, "@" .. SpeciesGeometry.TABLE_REL)
    if chunk then
      local ok, value = pcall(chunk)
      if ok and type(value) == "table" then
        _table = value
        _loadError = nil
        return _table, nil
      end
      _loadError = tostring(value)
    else
      _loadError = tostring(err)
    end
  end
  -- JSON fallback
  local raw = readBytes(mod or V.mod, SpeciesGeometry.JSON_REL)
  if type(raw) == "string" then
    local ok, data = pcall(JsonDecode.decode, raw)
    if ok and type(data) == "table" then
      local converted = {}
      for k, v in pairs(data) do
        local dex = tonumber(k)
        if dex and type(v) == "table" then converted[dex] = v end
      end
      _table = converted
      _loadError = nil
      return _table, nil
    end
  end
  _table = {}
  _loadError = _loadError or "species geometry table missing"
  return _table, _loadError
end

function SpeciesGeometry.clearCache()
  _table = nil
  _loadError = nil
end

function SpeciesGeometry.normalizeDex(speciesId)
  local n = tonumber(speciesId)
  if n and n >= 1 and n <= 151 then return math.floor(n) end
  return nil
end

function SpeciesGeometry.entryFor(speciesId, mod)
  local dex = SpeciesGeometry.normalizeDex(speciesId)
  if not dex then return nil, nil end
  local t = SpeciesGeometry.load(mod)
  return t[dex], dex
end

local function packFrameWidth(entry, packId)
  if type(entry) ~= "table" or type(entry.packs) ~= "table" then return nil end
  local preferred = {
    packId,
    "pokemmo",
    "followers",
    "pokedex",
    "swimming",
    "levitate",
  }
  for _, id in ipairs(preferred) do
    if type(id) == "string" then
      local pack = entry.packs[id]
      local fw = pack and tonumber(pack.frameWidth)
      if fw and fw > 0 then return fw end
    end
  end
  for _, pack in pairs(entry.packs) do
    local fw = type(pack) == "table" and tonumber(pack.frameWidth)
    if fw and fw > 0 then return fw end
  end
  return nil
end

--- Visual WIDTH used for follower spacing (body footprint, not height).
-- Prefers nativeVisualWidth; falls back to pack frameWidth; else Classic 16.
function SpeciesGeometry.visualWidth(speciesId, mod, opts)
  opts = opts or {}
  local entry = select(1, SpeciesGeometry.entryFor(speciesId, mod))
  if not entry then return SpeciesGeometry.CELL_PX end
  local nw = tonumber(entry.nativeVisualWidth)
  if nw and nw > 0 then return nw end
  local sw = tonumber(entry.scaledVisualWidth)
  if sw and sw > 0 then return sw end
  return packFrameWidth(entry, opts.packId) or SpeciesGeometry.CELL_PX
end

--- Visible height hint for UI fitting (optional).
function SpeciesGeometry.visualHeight(speciesId, mod, opts)
  opts = opts or {}
  local entry = select(1, SpeciesGeometry.entryFor(speciesId, mod))
  if not entry then return SpeciesGeometry.CELL_PX end
  local nh = tonumber(entry.nativeVisualHeight)
  if nh and nh > 0 then return nh end
  local sh = tonumber(entry.scaledVisualHeight)
  if sh and sh > 0 then return sh end
  if type(entry.packs) == "table" then
    local pack = entry.packs[opts.packId or "pokemmo"]
      or entry.packs.pokemmo
      or entry.packs.followers
    local fh = pack and tonumber(pack.frameHeight)
    if fh and fh > 0 then return fh end
  end
  return SpeciesGeometry.CELL_PX
end

local function clamp(n, lo, hi)
  if n < lo then return lo end
  if n > hi then return hi end
  return n
end

local function overhangPx(width)
  return math.max(0, (tonumber(width) or SpeciesGeometry.CELL_PX) - SpeciesGeometry.CELL_PX)
end

--- Continuous desired visual gap in pixels between two convoy members.
-- previousSpeciesId nil → trainer (~16px). Uses WIDTH overhang only.
function SpeciesGeometry.desiredFollowGapPx(previousSpeciesId, currentSpeciesId, mod, opts)
  opts = opts or {}
  local frontW = SpeciesGeometry.CELL_PX
  if previousSpeciesId ~= nil then
    frontW = SpeciesGeometry.visualWidth(previousSpeciesId, mod, opts)
  end
  local backW = SpeciesGeometry.visualWidth(currentSpeciesId, mod, opts)
  local gap = SpeciesGeometry.CELL_PX
    + overhangPx(frontW) * SpeciesGeometry.FRONT_OVERHANG_FACTOR
    + overhangPx(backW) * SpeciesGeometry.BACK_OVERHANG_FACTOR

  local curDex = SpeciesGeometry.normalizeDex(currentSpeciesId)
  local prevDex = SpeciesGeometry.normalizeDex(previousSpeciesId)
  local ov = (curDex and SpeciesGeometry.FOLLOW_GAP_PX_OVERRIDES[curDex])
    or (prevDex and SpeciesGeometry.FOLLOW_GAP_PX_OVERRIDES[prevDex])
  local hasOverride = type(ov) == "number" and ov > 0
  if hasOverride then
    gap = math.max(gap, ov)
  end

  local maxPx = hasOverride
    and SpeciesGeometry.GAP_PX_OVERRIDE_MAX
    or SpeciesGeometry.GAP_PX_TYPICAL_MAX
  return clamp(gap, SpeciesGeometry.GAP_PX_MIN, maxPx)
end

--- Map a desired pixel gap to a discrete trail-cell lag (no sticky state).
-- Caps at 2 cells — exceptional 3-cell jumps are retired.
function SpeciesGeometry.cellsForGapPx(gapPx)
  gapPx = tonumber(gapPx) or SpeciesGeometry.CELL_PX
  if gapPx >= SpeciesGeometry.GAP_HYSTERESIS_UP_PX then
    return 2
  end
  return 1
end

--- Sticky hysteresis helper: avoid oscillating 1↔2 around the midpoint.
function SpeciesGeometry.applyGapHysteresis(gapPx, stickyCells)
  gapPx = tonumber(gapPx) or SpeciesGeometry.CELL_PX
  local sticky = math.floor(tonumber(stickyCells) or 1)
  if sticky < 1 then sticky = 1 end
  if sticky > 2 then sticky = 2 end
  if sticky <= 1 then
    if gapPx >= SpeciesGeometry.GAP_HYSTERESIS_UP_PX then return 2 end
    return 1
  end
  if gapPx < SpeciesGeometry.GAP_HYSTERESIS_DOWN_PX then return 1 end
  return 2
end

--- Derive a spacing class from native / scaled visual height when present.
local function classFromNativeHeight(h)
  h = tonumber(h) or 0
  if h <= 16 then return "XS" end
  if h <= 20 then return "S" end
  if h <= 24 then return "M" end
  if h <= 29 then return "L" end
  if h <= 35 then return "XL" end
  return "XXL"
end

--- Desired follower trail distance in cells for a species (visual only).
-- Continuous width→px→cells (no sticky). Classic callers still get 1 via
-- VariableSize.visualFollowGap when True Size is inactive.
function SpeciesGeometry.followGap(speciesId, mod)
  local px = SpeciesGeometry.desiredFollowGapPx(nil, speciesId, mod)
  return SpeciesGeometry.cellsForGapPx(px)
end

--- Spacing between two convoy members from the pair's desired visual gap.
function SpeciesGeometry.followGapBetween(previousSpeciesId, currentSpeciesId, mod)
  local px = SpeciesGeometry.desiredFollowGapPx(previousSpeciesId, currentSpeciesId, mod)
  return SpeciesGeometry.cellsForGapPx(px)
end

-- packId: followers | pokemmo | pokedex | swimming | levitate
function SpeciesGeometry.packGeometry(speciesId, packId, mod)
  local entry, dex = SpeciesGeometry.entryFor(speciesId, mod)
  if not entry or type(entry.packs) ~= "table" then return nil, dex end
  local pack = entry.packs[packId]
  if type(pack) ~= "table" then return nil, dex end
  return pack, dex, entry
end

function SpeciesGeometry.relativePath(speciesId, packId, variant, mod)
  local pack = SpeciesGeometry.packGeometry(speciesId, packId, mod)
  if not pack or type(pack.relativeDir) ~= "string" then return nil end
  local dex = SpeciesGeometry.normalizeDex(speciesId)
  if not dex then return nil end
  local v = (variant == "shiny" or variant == "s" or variant == true) and "shiny" or "normal"
  return string.format("%s/%03d-%s.png", pack.relativeDir, dex, v), pack
end

-- Back-compat alias used by the Charizard prototype.
SpeciesGeometry.prototypeRelativePath = SpeciesGeometry.relativePath
SpeciesGeometry.overrideFor = SpeciesGeometry.entryFor
SpeciesGeometry.OVERRIDES = nil -- deprecated; use generated table

function SpeciesGeometry.summary(mod)
  local t = SpeciesGeometry.load(mod)
  local n, classes, overrides = 0, {}, 0
  for dex, e in pairs(t) do
    if type(dex) == "number" and type(e) == "table" then
      n = n + 1
      local c = e.class or "?"
      if e.nativeVisualHeight and e.nativeVisualHeight > 0 then
        c = classFromNativeHeight(e.nativeVisualHeight)
      elseif e.scaledVisualHeight and e.scaledVisualHeight > 0 then
        c = classFromNativeHeight(e.scaledVisualHeight)
      end
      classes[c] = (classes[c] or 0) + 1
      if e.manualOverride then overrides = overrides + 1 end
    end
  end
  return {
    species = n,
    classes = classes,
    manualOverrides = overrides,
    loadError = _loadError,
  }
end

return SpeciesGeometry
