-- Central species visual geometry for True Size (visual only; 1-cell footprint).
-- Data generated by tools/generate_true_size_runtime.py into
-- assets/generated/true_size/species_table.lua (+ species_geometry.json).
local V = ...
local JsonDecode = V.require("json_decode")

local SpeciesGeometry = {}

SpeciesGeometry.SIZE_CLASSES = {
  XS  = { minH = 14, maxH = 16, label = "XS" },
  S   = { minH = 17, maxH = 20, label = "S" },
  M   = { minH = 21, maxH = 24, label = "M" },
  L   = { minH = 25, maxH = 29, label = "L" },
  XL  = { minH = 30, maxH = 35, label = "XL" },
  XXL = { minH = 36, maxH = 42, label = "XXL" },
}

SpeciesGeometry.TABLE_REL = "assets/generated/true_size/species_table.lua"
SpeciesGeometry.JSON_REL = "assets/generated/true_size/species_geometry.json"

local _table = nil
local _loadError = nil

local function readBytes(mod, rel)
  if mod and type(mod.read) == "function" then
    local ok, data = pcall(mod.read, mod, rel)
    if ok and type(data) == "string" and data ~= "" then return data end
  end
  local f = io.open(rel, "rb")
  if not f and V.path then
    f = io.open((V.path or ".") .. "/" .. rel, "rb")
  end
  if f then
    local data = f:read("*a")
    f:close()
    if type(data) == "string" and data ~= "" then return data end
  end
  return nil
end

function SpeciesGeometry.load(mod)
  if _table ~= nil then return _table, _loadError end
  local src = readBytes(mod or V.mod, SpeciesGeometry.TABLE_REL)
  if type(src) == "string" then
    local loader = loadstring or load
    local chunk, err = loader(src, "@" .. SpeciesGeometry.TABLE_REL)
    if chunk then
      local ok, value = pcall(chunk)
      if ok and type(value) == "table" then
        _table = value
        _loadError = nil
        return _table, nil
      end
      _loadError = tostring(value)
    else
      _loadError = tostring(err)
    end
  end
  -- JSON fallback
  local raw = readBytes(mod or V.mod, SpeciesGeometry.JSON_REL)
  if type(raw) == "string" then
    local ok, data = pcall(JsonDecode.decode, raw)
    if ok and type(data) == "table" then
      local converted = {}
      for k, v in pairs(data) do
        local dex = tonumber(k)
        if dex and type(v) == "table" then converted[dex] = v end
      end
      _table = converted
      _loadError = nil
      return _table, nil
    end
  end
  _table = {}
  _loadError = _loadError or "species geometry table missing"
  return _table, _loadError
end

function SpeciesGeometry.clearCache()
  _table = nil
  _loadError = nil
end

function SpeciesGeometry.normalizeDex(speciesId)
  local n = tonumber(speciesId)
  if n and n >= 1 and n <= 151 then return math.floor(n) end
  return nil
end

function SpeciesGeometry.entryFor(speciesId, mod)
  local dex = SpeciesGeometry.normalizeDex(speciesId)
  if not dex then return nil, nil end
  local t = SpeciesGeometry.load(mod)
  return t[dex], dex
end

-- packId: followers | pokemmo | pokedex | swimming | levitate
function SpeciesGeometry.packGeometry(speciesId, packId, mod)
  local entry, dex = SpeciesGeometry.entryFor(speciesId, mod)
  if not entry or type(entry.packs) ~= "table" then return nil, dex end
  local pack = entry.packs[packId]
  if type(pack) ~= "table" then return nil, dex end
  return pack, dex, entry
end

function SpeciesGeometry.relativePath(speciesId, packId, variant, mod)
  local pack = SpeciesGeometry.packGeometry(speciesId, packId, mod)
  if not pack or type(pack.relativeDir) ~= "string" then return nil end
  local dex = SpeciesGeometry.normalizeDex(speciesId)
  if not dex then return nil end
  local v = (variant == "shiny" or variant == "s" or variant == true) and "shiny" or "normal"
  return string.format("%s/%03d-%s.png", pack.relativeDir, dex, v), pack
end

-- Back-compat alias used by the Charizard prototype.
SpeciesGeometry.prototypeRelativePath = SpeciesGeometry.relativePath
SpeciesGeometry.overrideFor = SpeciesGeometry.entryFor
SpeciesGeometry.OVERRIDES = nil -- deprecated; use generated table

function SpeciesGeometry.summary(mod)
  local t = SpeciesGeometry.load(mod)
  local n, classes, overrides = 0, {}, 0
  for dex, e in pairs(t) do
    if type(dex) == "number" and type(e) == "table" then
      n = n + 1
      local c = e.class or "?"
      classes[c] = (classes[c] or 0) + 1
      if e.manualOverride then overrides = overrides + 1 end
    end
  end
  return {
    species = n,
    classes = classes,
    manualOverrides = overrides,
    loadError = _loadError,
  }
end

return SpeciesGeometry
